# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc242d9518b78c72608bd1c051cf2e3e1389d993e8c557729e3e32d0258de6e32d548615e6a21cc891ea7f9f445723ad1935684fed338e5bb7fe9ed141b248a

test:
  secret_key_base: c1e7405e4b671a96abcf5ebf8980d432d2e670a0e7690bf316b813c41efc941d45b2ebda0191389fe6dc89e177326a210131fe0d30564cc0c37bc73e8098fe75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
